### ISSUE TITLE
Ignore messages starting with "is"

### ISSUE THREAD

**Issue by alimac** [alimac/err-factoid#1]
```
2015-11-09 07:25:32,422 ERROR    errbot.errBot             An error happened while processing a message ("is something something?"): Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/errbot/errBot.py", line 374, in _execute_and_send
    reply = commands[cmd](mess, match) if match else commands[cmd](mess, args)
  File "/home/alimac/errbot/Factoid/factoid.py", line 25, in tell_factoid
    if self.factoid_store[factoid]:
KeyError: u'is something something'
"
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/errbot/errBot.py", line 374, in _execute_and_send
    reply = commands[cmd](mess, match) if match else commands[cmd](mess, args)
  File "/home/alimac/errbot/Factoid/factoid.py", line 25, in tell_factoid
    if self.factoid_store[factoid]:
KeyError: u'is something something'
```

**Comment by alimac** [comment]
Resolved by requiring that learning factoids must be prefixed. Bot will react to "Err, water is wet", but not plain "water is wet"
